gaia_a08:
  url: ${GAIA_A08_URL:-}
  poll_interval: 65

waqi:
  enabled: ${WAQI_ENABLED:-false}
  token: ${WAQI_TOKEN:-}
  url: ${WAQI_URL:-https://api.waqi.info/feed/here/}
  poll_interval: 300

database:
  type: "sqlite"
  sqlite_path: "./sqlite/air_quality.db"