services:
  air-quality-monitor:
    build: .
    container_name: air_quality_monitor
    restart: unless-stopped
    ports:
      - "8008:8008" 
    volumes:
      - ./sqlite/air_quality.db:/app/sqlite/air_quality.db
